// <auto-generated />
using System;
using Data.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DumpDriveDbContext))]
    [Migration("20241225171229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is my resume file.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(174),
                            FileId = 1,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(316),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Great vacation photo!",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(459),
                            FileId = 3,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(459),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "I love this holiday song.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(461),
                            FileId = 4,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(461),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "This is a great report!",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(462),
                            FileId = 5,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(463),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "This is an awesome movie!",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(465),
                            FileId = 8,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(466),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the content of my resume.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(8650),
                            FolderId = 1,
                            Name = "Resume.pdf",
                            OwnerId = 1,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(8798)
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is the content of my presentation.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9071),
                            FolderId = 2,
                            Name = "Presentation.pptx",
                            OwnerId = 2,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9072)
                        },
                        new
                        {
                            Id = 3,
                            Content = "A beautiful vacation photo content.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9074),
                            FolderId = 2,
                            Name = "Vacation.jpeg",
                            OwnerId = 3,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9074)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Audio content of a holiday song.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9075),
                            FolderId = 3,
                            Name = "Holiday.mp3",
                            OwnerId = 4,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9076)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Content for my project report.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9077),
                            FolderId = 4,
                            Name = "Report.xlsx",
                            OwnerId = 5,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9077)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Content of a holiday song in MP3 format.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9080),
                            FolderId = 3,
                            Name = "Song.mp3",
                            OwnerId = 1,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9081)
                        },
                        new
                        {
                            Id = 7,
                            Content = "This is a document content.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9082),
                            FolderId = 5,
                            Name = "Document.docx",
                            OwnerId = 2,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9082)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Video file content for a movie.",
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9083),
                            FolderId = 5,
                            Name = "Movie.mp4",
                            OwnerId = 3,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(9084)
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7113),
                            Name = "Documents",
                            OwnerId = 1,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7262)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7414),
                            Name = "Photos",
                            OwnerId = 2,
                            ParentFolderId = 1,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7415)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7417),
                            Name = "Music",
                            OwnerId = 3,
                            ParentFolderId = 1,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7418)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7419),
                            Name = "Projects",
                            OwnerId = 4,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7419)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7421),
                            Name = "Videos",
                            OwnerId = 5,
                            ParentFolderId = 4,
                            UpdatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(7421)
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.SharedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SharedItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SharedUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SharedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OwnerUserId = 1,
                            SharedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(1647),
                            SharedItemType = "File",
                            SharedUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            OwnerUserId = 3,
                            SharedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(1923),
                            SharedItemType = "Folder",
                            SharedUserId = 4
                        },
                        new
                        {
                            Id = 3,
                            OwnerUserId = 4,
                            SharedAt = new DateTime(2024, 12, 25, 17, 12, 29, 133, DateTimeKind.Utc).AddTicks(1924),
                            SharedItemType = "File",
                            SharedUserId = 5
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 127, DateTimeKind.Utc).AddTicks(7610),
                            Email = "johndoe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "AQAAAAEAACcQAAAAEBZ4BfJwUIMIUCXXxRwj8lhgefiscpN2jVuihOt8vdB1MM9TaxiOXTaVvqXsEA3vpQ=="
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 128, DateTimeKind.Utc).AddTicks(9178),
                            Email = "janesmith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "AQAAAAEAACcQAAAAEJL7fjSdK2AWe1mCOaidJgvCVXGP+P8kkLPwXThG7W0FktYxHI9chAZe0PjUXgJnfw=="
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 129, DateTimeKind.Utc).AddTicks(9732),
                            Email = "michaeljohnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Password = "AQAAAAEAACcQAAAAEMYrVSa+t5w5whb+8FHVbfGTc/DvZOjrfHdtPVZMME5c5WavrfEUKytbgmFgozMDzg=="
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 131, DateTimeKind.Utc).AddTicks(649),
                            Email = "emilydavis@example.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            Password = "AQAAAAEAACcQAAAAEPcTkRXifSWvt/IpXDlcZ35i2Z28C+Ti2+OfiPw9BXeLN82/Cjec0DZyM2o/hcOIcw=="
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 25, 17, 12, 29, 132, DateTimeKind.Utc).AddTicks(1154),
                            Email = "davidlee@example.com",
                            FirstName = "David",
                            LastName = "Lee",
                            Password = "AQAAAAEAACcQAAAAEL3M1Hs9ldanWq9iW+S2RmIh+5zJdzS6jec6Ez/jWkmTPPkT6d35PyAmLG9LNLIewg=="
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.Comment", b =>
                {
                    b.HasOne("Data.Entities.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Models.User", "Owner")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Data.Entities.Models.File", b =>
                {
                    b.HasOne("Data.Entities.Models.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Models.User", "Owner")
                        .WithMany("Files")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Data.Entities.Models.Folder", b =>
                {
                    b.HasOne("Data.Entities.Models.User", "Owner")
                        .WithMany("Folders")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Models.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Data.Entities.Models.SharedItem", b =>
                {
                    b.HasOne("Data.Entities.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.Models.User", "SharedUser")
                        .WithMany()
                        .HasForeignKey("SharedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.Models.User", null)
                        .WithMany("SharedItems")
                        .HasForeignKey("UserId");

                    b.Navigation("OwnerUser");

                    b.Navigation("SharedUser");
                });

            modelBuilder.Entity("Data.Entities.Models.Folder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("Data.Entities.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Files");

                    b.Navigation("Folders");

                    b.Navigation("SharedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
